### PR TITLE
Adding force resize checkbox to allow overriding an existing DC/OS deployment without using pipelines

### PR DESCRIPTION
**Pull request by TrevinTeacutter**

### CODE REVIEW

**Comment by mtweten** [comment]
Did we want to add checkboxes to any other operations, like destroy or create?

**Comment by TrevinTeacutter** [comment]
We decided against it because they use the confirmationModal core stuff to do quite a bit, we would essentially have to write our own from what I understood much like we did with resize and that was more effort than Will thought was necessary. As long as there is one way to do it without a pipeline, even if it is specific, it was felt good enough.

**Review by mtweten — APPROVED** [review]

**Comment by willgorman** [comment]
Do we have the ability to easily add help text for this element?  If so, it'd be good to mention why it might be useful.

**Comment by TrevinTeacutter** [comment]
Yeah, we can add that in.

**Review by willgorman — APPROVED** [review]

**Pull request merged**
